services:
  postgres:
    image: postgres:18.3
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME:-enviodb}
      POSTGRES_USER: ${POSTGRES_USERNAME:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - envio_postgres_data:/var/lib/postgresql
    networks:
      - envio-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.6.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - envio_redis_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD:-password}
    networks:
      - envio-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-password}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  envio_postgres_data:
  envio_redis_data:

networks:
  envio-network:
    driver: bridge
