-- @formatter:off

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_github_id VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS user_github_id VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS user_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) WITHOUT TIME ZONE;

UPDATE users
SET user_github_id = CONCAT('legacy-', MD5(ctid::TEXT))
WHERE user_github_id IS NULL;

UPDATE users
SET email = CONCAT(user_github_id, '@users.noreply.github.com')
WHERE email IS NULL;

UPDATE users
SET role = 'VIEWER'
WHERE role IS NULL;

ALTER TABLE users ALTER COLUMN user_github_id SET NOT NULL;
ALTER TABLE users ALTER COLUMN email SET NOT NULL;
ALTER TABLE users ALTER COLUMN role SET DEFAULT 'VIEWER';
ALTER TABLE users ALTER COLUMN role SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_users_github_id
    ON users (user_github_id);

CREATE TABLE IF NOT EXISTS user_devices (
    user_device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    device_name VARCHAR(255) NOT NULL,
    public_key TEXT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE user_devices ADD COLUMN IF NOT EXISTS user_device_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE user_devices ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE user_devices ADD COLUMN IF NOT EXISTS device_name VARCHAR(255);
ALTER TABLE user_devices ADD COLUMN IF NOT EXISTS public_key TEXT;
ALTER TABLE user_devices ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE user_devices ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) WITHOUT TIME ZONE;

UPDATE user_devices
SET device_name = 'legacy-device'
WHERE device_name IS NULL;

UPDATE user_devices
SET public_key = 'ssh-ed25519 legacy'
WHERE public_key IS NULL;

DELETE FROM user_devices
WHERE user_id IS NULL
    OR NOT EXISTS (
        SELECT 1
        FROM users
        WHERE users.user_id = user_devices.user_id
    );

ALTER TABLE user_devices ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE user_devices ALTER COLUMN device_name SET NOT NULL;
ALTER TABLE user_devices ALTER COLUMN public_key SET NOT NULL;

ALTER TABLE user_devices DROP CONSTRAINT IF EXISTS fk_user_devices_user;

ALTER TABLE user_devices
    ADD CONSTRAINT fk_user_devices_user
    FOREIGN KEY (user_id)
    REFERENCES users(user_id)
    ON DELETE CASCADE;
